import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ListTodo } from "lucide-react";
import "./globals.css";
import {
    ClerkProvider,
    SignInButton,
    SignedIn,
    SignedOut,
    UserButton,
} from "@clerk/nextjs";

// Load fonts with CSS variables for Tailwind
const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ClerkProvider>
            <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
            <body className="bg-base-100">
            <header>
                <div className="navbar bg-base-100 shadow-sm justify-between">
                    <a className="btn btn-ghost text-xl text-primary flex items-center gap-2">
                        <ListTodo />
                        TODO
                    </a>
                    <div className="flex gap-2">
                        <SignedIn>
                            <UserButton />
                        </SignedIn>
                        <SignedOut>
                            <SignInButton mode="modal">
                                <button className="btn btn-primary">Sign In</button>
                            </SignInButton>
                        </SignedOut>
                    </div>
                </div>
            </header>

            <main>
                <SignedIn>{children}</SignedIn>
                <SignedOut>
                    <div className="flex items-center justify-center h-[80vh]">
                        <div className="text-center">
                            <p className="text-lg mb-4">Please sign in to continue</p>
                            <SignInButton mode="modal">
                                <button className="btn btn-primary">Sign In</button>
                            </SignInButton>
                        </div>
                    </div>
                </SignedOut>
            </main>
            </body>
            </html>
        </ClerkProvider>
    );
}
